## <font color='darkblue'>Section2 - Numpy</font>
This notebook is created from udemy course "<b>[Deep Learning Prerequisites: The Numpy Stack in Python](https://www.udemy.com/course/deep-learning-prerequisites-the-numpy-stack-in-python/learn/lecture/19643200#overview)</b>" which introducts Numpy, Scipy, Pandas, and Matplotlib: prep for deep learning, machine learning, and artificial intelligence.

<a id='s1'></a>
## <font color='darkblue'>Numpy Section Introduction</font>
([link](https://www.udemy.com/course/deep-learning-prerequisites-the-numpy-stack-in-python/learn/lecture/19643370#overview))
* Low-level: what does <b>[Numpy](https://numpy.org/)</b> do?
* High-level: why do we need it?
* The core library used in AI/ML and central object of this library is [numpy array](https://numpy.org/doc/stable/reference/generated/numpy.array.html).
* One sentence summary: "Linear algebra and a bit of probability"

### <font color='darkgreen'>Vectors and Matrics</font>
* In Linear Algebra, convention to treat vectors as 2D
* But not in Numpy! Vectors will be 1D (most of the time)
![VectorAndMatrix](images/S2_1.PNG)
<br/>

### <font color='darkgreen'>Dot Product/Inner Product</font>
* [Dot product](https://en.wikipedia.org/wiki/Dot_product) is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number.
![VectorAndMatrix](images/S2_2.PNG)
<br/>

### <font color='darkgreen'>Matrix Multiplication (C=AB)</font>
* [Matrix multiplication](https://en.wikipedia.org/wiki/Matrix_multiplication) as generalized dot product:
![VectorAndMatrix](images/S2_3.PNG)
<br/>

### <font color='darkgreen'>Element-wise product</font>
* Not so common in Linear Algebra, very common in ML:
![VectorAndMatrix](images/S2_4.PNG)
<br/>

### <font color='darkgreen'>And many more</font>
* Linear systems: Ax = b
* Inverse: $A^-1$
* [Determinant: |A|](https://en.wikipedia.org/wiki/Determinant)
* Choosing random numbers (e.g. Uniform, Gaussian)

### <font color='darkgreen'>Applications</font>
* Linear Regression
* Logistic Regression
* Deep Neural Networks
* SVM
* Principal Components Analysis
* K-Means clustering
* Control systems
* Game Theory
* Operations Research
* Portfolio Optimization

<a id='s2'></a>
## <font color='darkblue'>Array vs List</font>
([link](https://www.udemy.com/course/deep-learning-prerequisites-the-numpy-stack-in-python/learn/lecture/19643378#overview))
We are going to tell the difference between Array in numpy and normal Python list:

In [1]:
import numpy as np

L = [1, 2, 3]  # Normal Python List
A = np.array(L)

We initialize a list and an numpy array as above. Now let's iterate them:

In [2]:
for e in L:
    print(e)

1
2
3


In [3]:
for e in A:
    print(e)

1
2
3


Add item to list and array:

In [4]:
L.append(4); print(L)

[1, 2, 3, 4]


In [5]:
L + [5]

[1, 2, 3, 4, 5]

In [6]:
# Not as our expectation to be [1,2,3,4]
# instead, the result is that all element in array will be added by 4
# and get [1+4, 2+4, 3+4] = [5,6,7]
A + np.array([4])

array([5, 6, 7])

In [7]:
A + [1,2,3]  # = [1+1,2+2,3+3] = [2, 4, 6]

array([2, 4, 6])

In [8]:
2 * A

array([2, 4, 6])

In [9]:
2 * L # = L + L

[1, 2, 3, 4, 1, 2, 3, 4]

To do multiplication on every element in list:

In [10]:
list(map(lambda e: e*2, L)) # function map

[2, 4, 6, 8]

In [11]:
[e*2 for e in L] # List apprehension

[2, 4, 6, 8]

There are many common functions in numpy to process every element in array ([more](https://numpy.org/doc/stable/reference/routines.math.html)):

In [12]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [13]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

<a id='s3'></a>
## <font color='darkblue'>Dot Product</font>
([link](https://www.udemy.com/course/deep-learning-prerequisites-the-numpy-stack-in-python/learn/lecture/19643380#overview)) Check more numpy functionalities:

In [14]:
a = np.array([1,2])
b = np.array([3,4])

In [15]:
# Using for loop to do dot product
dot = 0
for e, f in zip(a, b):
    dot += e * f
    
dot

11

In [16]:
# Another way to do dot product
np.sum(a * b)  # = (a*b).sum()

11

In [17]:
# Using built-in funciton
np.dot(a, b)

11

In [18]:
# Or more intuitively
a.dot(b)

11

In [19]:
# or fancy way
a @ b

11

Let's check some Linear Algebra definitions:
![VectorAndMatrix](images/S2_5.PNG)
<br/>

In [20]:
# ||a||
amag = np.sqrt((a*a).sum())
amag

2.23606797749979

Or you can leverage exist package <b>[numpy.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html)</b>:

In [21]:
np.linalg.norm(a)

2.23606797749979

So the cosine between `a` and `b` will be:

In [22]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [23]:
np.arccos(cosangle) # unit as radian: https://en.wikipedia.org/wiki/Radian

0.17985349979247847

<a id='s4'></a>
## <font color='darkblue'>Speed Test</font>
([link](https://www.udemy.com/course/deep-learning-prerequisites-the-numpy-stack-in-python/learn/lecture/19643384#overview)) Let's check the performance difference on dot product between Python list and numpy array.

In [24]:
from datetime import datetime

def time_diff(func):
    def wrapper(A, B):
        st = datetime.now()
        out = func(A, B)
        diff = datetime.now() - st
        return diff, out
    
    return wrapper

@time_diff
def dot_product_by_for_loop(A, B):
    st = datetime.now()
    dot = 0
    for a, b in zip(A,B):
        dot += a * b
        
    return dot

@time_diff
def dot_product_by_numpy_style(A, B):
    return A.dot(B)

perf_datas = []
for array_size in range(1000000, 2000000, 100000):
    A = np.random.rand(array_size)
    B = np.random.rand(array_size)

    
    t1, dot1 = dot_product_by_for_loop(A, B)
    t2, dot2 = dot_product_by_numpy_style(A, B)

    # print("dot1={}/dot2={}".format(dot1, dot2))
    print("Numpy style is faster for {:.02f} times!".format(t1.total_seconds()/t2.total_seconds()))
    perf_datas.append(t1.total_seconds()/t2.total_seconds())

Numpy style is faster for 385.63 times!
Numpy style is faster for 466.36 times!
Numpy style is faster for 535.79 times!
Numpy style is faster for 653.76 times!
Numpy style is faster for 622.94 times!
Numpy style is faster for 320.22 times!
Numpy style is faster for 350.94 times!
Numpy style is faster for 359.65 times!
Numpy style is faster for 377.56 times!
Numpy style is faster for 394.04 times!


In [25]:
print("Numpy is faster than for loop for {:.02f}-{:.02f} times!".format(max(perf_datas), min(perf_datas)))

Numpy is faster than for loop for 653.76-320.22 times!


<a id='s5'></a>
## <font color='darkblue'>Matrics</font>
([link](https://www.udemy.com/course/deep-learning-prerequisites-the-numpy-stack-in-python/learn/lecture/19643388#overview)) Let's check <b>[numpy.matrix](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html)</b>

In [26]:
L = [[1,2], [3,4]]
A = np.array(L)
A

array([[1, 2],
       [3, 4]])

Let's check how to play with this matrix like array:

In [27]:
A[0, 1]  # = L[0][1]

2

In [28]:
A[:, 0]  # Get first element of every row

array([1, 3])

In [29]:
np.exp(A) # Calculate exponential of every element

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [30]:
B = np.array([[1,2,3], [4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# A dot B
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [32]:
np.linalg.det(A)

-2.0000000000000004

In [33]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [34]:
# Get matrix Identity matrix
# https://en.wikipedia.org/wiki/Identity_matrix
np.linalg.inv(A).dot(A) 

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [35]:
np.trace(A)

5

In [36]:
np.diag(A)

array([1, 4])

In [37]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [38]:
# https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors
Lam, V = np.linalg.eig(A)
V

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [39]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [40]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [41]:
np.allclose(V @ np.diag(Lam), A @ V)

True

<a id='s6'></a>
## <font color='darkblue'>Solving Linear Systems</font>
([link](https://www.udemy.com/course/deep-learning-prerequisites-the-numpy-stack-in-python/learn/lecture/19643390#overview)) The admission fee at a small fair is \\$1.5 for children and \\$4 for adults. On a certain day, 2,200 people enter the fair and $5050 is collected. How many children and how many adults attend?<br/>
![VectorAndMatrix](images/S2_6.PNG)
<br/>

Above equation can be expressed by matrix as below:
![VectorAndMatrix](images/S2_7.PNG)
<br/>

### <font color='darkgreen'>Don't do that literally!</font>
* The "inverse" is slower and less accurate
* There are better algorithms to solve linear systems
```pyhton
x = np.linalg.solve(A, b) # yes
x = np.linalg.inv(A).dot(b) # no
```

In [42]:
A = np.array([[1,1], [1.5, 4]])
b = np.array([2200, 5050])

In [43]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [44]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

<a id='s7'></a>
## <font color='darkblue'>Generating Data</font>
([link](https://www.udemy.com/course/deep-learning-prerequisites-the-numpy-stack-in-python/learn/lecture/19643396#overview)) Let's check a few methods in numpy to generate data ([Array creation routines](https://numpy.org/doc/stable/reference/routines.array-creation.html)):

In [45]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.random.random((2, 3))

array([[0.17345281, 0.46932682, 0.06605455],
       [0.34730238, 0.21234493, 0.8294856 ]])

In [49]:
# number is generated by normal distribution
np.random.randn(2, 3)

array([[ 1.03188099, -0.76849746,  0.98229427],
       [ 0.44517005, -0.39458272,  0.63536388]])

In [50]:
R = np.random.randn(10000)

In [51]:
R.mean() # = np.mean(R)

-0.0016408931336383346

In [52]:
R.std()

0.9970056699986533

In [53]:
R.var()

0.9940203060094635

In [54]:
R = np.random.randn(10000, 3)

In [55]:
R.mean(axis=0)

array([-0.01215554,  0.00712237,  0.01459562])

In [56]:
R.mean(axis=1)

array([-0.44923692,  1.09969312, -0.23758334, ...,  0.32469015,
       -0.28590611,  0.39923162])

In [57]:
R.shape

(10000, 3)

In [58]:
np.cov(R.T).shape #  = np.cov(R, rowvar=False)

(3, 3)

In [59]:
# https://docs.scipy.org/doc//numpy-1.11.0/reference/generated/numpy.random.randint.html
np.random.randint(0, 10, size=(3,3))

array([[6, 0, 2],
       [0, 1, 1],
       [6, 3, 0]])

In [60]:
# https://docs.scipy.org/doc//numpy-1.10.4/reference/generated/numpy.random.choice.html
np.random.choice(10, size=(3,3))

array([[1, 6, 3],
       [2, 5, 1],
       [2, 2, 7]])

<a id='s8'></a>
## <font color='darkblue'>Numpy Exercise</font>
([link](https://www.udemy.com/course/deep-learning-prerequisites-the-numpy-stack-in-python/learn/lecture/19643400#overview))
* I will not provide the solution - you should discuss the problem with your peers using the forum
* Earlier, we did a speed test to compare list vs. array dot product
* Do a similar speed test, but for matrix multiplication
* You will have to implement matrix multiplication for lists

In [61]:
@time_diff
def mm_by_for_loop(m1, m2):
    new_matrix_shape = (m1.shape[0], m2.shape[1])
    new_matrix = np.zeros(new_matrix_shape)
    for ri, row in enumerate(m1):
        for ci, col in enumerate(m2.T):
            new_matrix[ri, ci] = np.sum(row * col)
            
    return new_matrix


@time_diff
def mm_by_numpy_style(m1, m2):
    return m1.dot(m2)

# m1 = np.array([[1,2], [3,4]])
# m2 = np.array([[1,2,3], [4,5,6]])

In [62]:
perf_datas = []
for array_size in range(500, 1000, 100):
    m1 = np.random.randn(array_size, array_size)
    m2 = np.random.randn(array_size, array_size)

    
    t1, m3 = mm_by_for_loop(m1, m2)
    t2, m3 = mm_by_numpy_style(m1, m2)

    # print("dot1={}/dot2={}".format(dot1, dot2))
    print("Numpy style is faster for {:.02f} times!".format(t1.total_seconds()/t2.total_seconds()))
    perf_datas.append(t1.total_seconds()/t2.total_seconds())

Numpy style is faster for 752.99 times!
Numpy style is faster for 497.84 times!
Numpy style is faster for 512.49 times!
Numpy style is faster for 565.53 times!
Numpy style is faster for 592.02 times!
